### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ahalves** [anilabhadatta/educative-viewer#5]
The server indexes the folders as expected, but as soon as I click on one, it gives me the following error:
![image](https://user-images.githubusercontent.com/127245078/224675028-4e021bca-b58b-4d64-9d58-316969ee6b1e.png)

The files:
![image](https://user-images.githubusercontent.com/127245078/224674718-0d99351a-83bc-4826-a81c-97674d4e4af0.png)
etc...

**Comment by anilabhadatta** [comment]
@ahalves send me the zip file of those files

**Comment by anilabhadatta** [comment]
@ahalves As far as i can decode, the html contains katex/ latex code which causes issues with the JINJA template engine of Flask.

**Comment by anilabhadatta** [comment]
@ahalves Fixed this issue, please clone the latest version
