### ISSUE TITLE
Unable to read because of this weird button!!

### ISSUE THREAD

**Issue by Mohamed-SayedAlAhl** [anilabhadatta/educative-viewer#7]
Hi,
I liked your work, and the new scrapper is working, but the viewer seems to have an issue. This weird button doesn't belong and make me unable to read, and it goes on when I scroll the page, which is annoying.
I hope you fix the issue.
Here is a screenshot of the button I am talking about: 
![044](https://user-images.githubusercontent.com/128070638/234895006-1c8581d5-7c12-4ebc-9929-100d78860cb4.png)

**Comment by Mohamed-SayedAlAhl** [comment]
@anilabhadatta 
Please help me

**Comment by anilabhadatta** [comment]
@Mohamed-SayedAlAhl I need the selector of that, Don't know from where it is showing.

**Comment by Mohamed-SayedAlAhl** [comment]
Hi @anilabhadatta,
It only appears when using the viewer, and not the HTML directly.
It was super annoying for me, I managed to block the element using Adguard extension

**Comment by anilabhadatta** [comment]
@Mohamed-SayedAlAhl i didn't notice that while using it in viewer.
